# https://starship.rs/config/#openstack

scan_timeout = 10

format = """
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$env_var\
$custom\
$sudo\
$python\
$cmd_duration\
$line_break\
$status\
$character"""

# $java\
# $ruby\

