# get the directory of this script even if symlinked
# works on linux and mac
zshrc_dir=$(dirname "$(realpath -- '$0')")
# this only works if not symlinked
# zshrc_dir=${0:a:h}

# could auto source files in a dir but I care about load order
zshrc_files=(
    path
    editor-pager
    plugins
    prompt
    history-ignore
    history
    commands
    fzf
    misc
)
zshrc_paths=($zshrc_dir'/'${^zshrc_files}'.zsh')
unset zshrc_files

# source files for error if does not exist
for f in $zshrc_paths; do
    . $f
done
unset zshrc_paths

# TODO: check and source .zshrc.local

