# profile zsh startup, comment out unless debugging loading times
# for i in $(seq 1 10); do /usr/bin/time zsh -i -c exit; done
# see end of file
######
# zmodload zsh/zprof

# get the directory of this script when symlinked works on linux and mac
zshrc_dir=$(dirname "$(realpath $ZDOTDIR/.zshrc)")
export DOTS_DIR=$(dirname $zshrc_dir)

autoload -Uz compinit
compinit -d

zshrc_files=(
    variables
    path
    editor-pager
    prompt
    history-ignore
    history
    misc
    fzf
    tmux
    commands
)
zshrc_paths=($zshrc_dir'/'${^zshrc_files}'.zsh')
unset zshrc_files

for f in $zshrc_paths; do
    if [[ -r $f ]]; then
        . $f
    else
        echo "'$f' does not exist."
    fi
done
unset zshrc_paths

if [[ -r ~/.zshrc.local ]]; then
    . ~/.zshrc.local
fi

# profile zsh startup, comment out unless debugging loading times
# see start of file
#####
# zprof
